name: Run Rapise Tests

on:
  workflow_dispatch:

jobs:
  run-rapise:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install Rapise
        shell: powershell
        run: |
          Write-Host "Installing Rapise..."
          npm install https://inflectra-rapise-nightly-installers.s3.eu-north-1.amazonaws.com/Rapise_9.0.35.24/rapise-9.0.35.24.tgz

      - name: Configure Rapise Launcher
        shell: powershell
        env:
          SPIRA_API_KEY: ${{ secrets.SPIRA_API_KEY }}
        run: |
          Write-Host "Configuring RapiseLauncher..."

          npx rapiselauncher `
            -c RepositoryConnection.xml `
            --set SpiraServer=https://televisa.spiraservice.net/ `
            --set SpiraUser=leonardo.cruz `
            --set SpiraPassword="$env:SPIRA_API_KEY" `
            --set AutomationHost=XXDARKANDRESXX

      - name: Execute SpiraTest Case 292
        shell: powershell
        run: |
          Write-Host "Executing SpiraTest case 292..."

          npx rapiselauncher `
            -c RepositoryConnection.xml `
            -t 292 `
            --details `
            --param "g_browserLibrary=Selenium - Chrome Headless"

      - name: Upload Rapise results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapise-results
          path: |
            .
            !node_modules
            $env:USERPROFILE\.rapise\temp
